AWSTemplateFormatVersion: "2010-09-09"

Description: deploying instance for project
Resources:
    SecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Allow ports 

            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 22
                  ToPort: 22
                  CidrIp: 0.0.0.0/0
                  
                - IpProtocol: tcp
                  FromPort: 8888
                  ToPort: 8888
                  CidrIp: 0.0.0.0/0

                - IpProtocol: tcp
                  FromPort: 6868
                  ToPort: 6868
                  CidrIp: 0.0.0.0/0    
            
    MyinstanceEC2:
        Type: AWS::EC2::Instance
        Properties:
            ImageId: ami-05cf1e9f73fbad2e2
            InstanceType: t2.micro
            KeyName: devops-project-key
            SecurityGroupIds:
                - !Ref SecurityGroup
    
Outputs:
    InstanceId:
        Value: !Ref MyinstanceEC2
            
